# Top-level identities module.
# Inspired by Catppuccin/nix options design:
#   - Global toggle (identities.enable)
#   - Per-identity enable (identities.<name>.enable)
#   - Tool-specific output control (identities.<name>.git, .jj, .sapling)
{ config, lib, ... }:

with lib;

{
  options.identities = {
    enable = mkEnableOption "all identity modules";

    git = {
      enable = mkEnableOption "git identity includes for all enabled identities" // {
        default = true;
      };

      includes = mkOption {
        type = types.listOf types.attrs;
        default = [ ];
        description = ''
          Git include entries generated by identity modules.
          Each entry is suitable for use in `programs.git.includes`.
        '';
        internal = true;
      };
    };

    jj = {
      enable = mkEnableOption "Jujutsu identity configs for all enabled identities" // {
        default = true;
      };
    };

    sapling = {
      enable = mkEnableOption "sapling identity config for all enabled identities" // {
        default = true;
      };
    };
  };
}
